export const Allstore = [
  {
    id: 1,
    image: "Images/Home/astarinchimes.png",
    title: "Astarin Chimes",
    url: "/store/astarinchimes ",
  },
  {
    id: 2,
    image: "Images/Home/boderry.jpg",
    title: "Boderry Watch Co",
    url: "/store/boderry",
  },
  {
    id: 3,
    image: "Images/Home/glamermaid.png",
    title: "Glamermaid",
    url: "/store/glamermaid ",
  },
  {
    id: 4,
    image: "Images/Home/Guduchi.png",
    title: "Guduchi Ayurveda",
    url: "/store/guduchi ",
  },
  {
    id: 5,
    image: "Images/Home/joybos_logo1.png",
    title: " Joybos",
    url: "/store/joybos ",
  },
  {
    id: 6,
    image: "Images/Home/luxepickleball1.png",
    title: "Luxe Pickle Ball",
    url: "/store/luxe ",
  },
  {
    id: 7,
    image: "Images/Home/mrpetcam.jpeg",
    title: "Mr.Petcam",
    url: "/store/petcam ",
  },
  {
    id: 8,
    image: "Images/Home/pineapple-island.png",
    title: " Pineapple Lsland",
    url: "/store/pineapple ",
  },
  {
    id: 9,
    image: "Images/Home/proteckd.png",
    title: "Proteck'd Apparel",
    url: "/store/proteck ",
  },
  {
    id: 10,
    image: "Images/Home/pyrofarms.jpeg",
    title: "PyroFarms",
    url: "/store/pyroFarms ",
  },
  {
    id: 11,
    image: "Images/Home/rhinousainc_(1).png",
    title: "Rhino USA",
    url: "/store/rhinoUSA ",
  },
  {
    id: 12,
    image: "Images/Home/ryzesuperfoods1.jpeg",
    title: "RYZE Superfoods",
    url: "/store/rYZE",
  },
  {
    id: 13,
    image: "Images/Home/sybotanica_logo.png",
    title: "Sybotanica",
    url: "/store/sybotanica ",
  },
  {
    id: 14,
    image: "Images/Home/tempest_(1).png",
    title: "Tempest Weather Flow",
    url: "/store/tempest ",
  },
  {
    id: 15,
    image: "Images/Home/tesgobike1.png",
    title: "tesgoCA",
    url: "/store/tesgoCA",
  },
  {
    id: 16,
    image: "Images/Home/triggeredbrand_(1).png",
    title: "The Triggered Brand",
    url: "/store/triggered",
  },
  {
    id: 17,
    image: "Images/Home/uvlizer.png",
    title: "Uvlizer",
    url: "/store/uvlizer",
  },
  {
    id: 18,
    image: "Images/Home/vitahotdeals.jpg",
    title: "VitaHotDeals",
    url: "/store/vitaHotDeals",
  },
  {
    id: 19,
    image: "Images/Home/YILONG_TATOO.png",
    title: "Yilong Tattooing",
    url: "/store/tattooing",
  },
  {
    id: 20,
    image: "Images/Home/yosepower1.png",
    title: " Yose Power",
    url: "/store/yose ",
  },
];
